CREATE TABLE `grafluxe_jetred`.`airports` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(4) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `location` VARCHAR(64) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
CHARSET=utf8
COLLATE utf8_general_ci
;

INSERT INTO `airports` (`code`, `name`, `location`)
  VALUES
    ("ALG", "Houari Boumedienne Airport", "Algiers"),
    ("AAE", "Rabah Bitat Airport", "Annaba"),
    ("BLJ", "Batna Airport", "Batna"),
    ("BJA", "Soummam Airport", "Bejaia"),
    ("BSK", "Biskra Airport", "Oumache"),
    ("CFK", "Chlef International Airport", "Chlef"),
    ("CZL", "Mohamed Boudiaf Airport", "Constantine"),
    ("HME", "Oued Irara Airport", "Hassi Messaoud"),
    ("GJL", "Jijel Ferhat Abbas Airport", "Jijel"),
    ("ORN", "Oran Es Senia Airport", "Oran"),
    ("QSF", "Ain Arnat Airport", "Sétif"),
    ("TMR", "Tamanrasset Airport", "Tamanrasset"),
    ("TLM", "Zenata Airport", "Tlemcen"),
    ("LAD", "Quatro de Fevereiro Airport", "Luanda"),
    ("SDD", "Lubango Airport", "Lubango"),
    ("COO", "Cadjehoun Airport", "Cotonou"),
    ("GBE", "Sir Seretse Khama International Airport", "Gaborone"),
    ("MUB", "Maun Airport", "Maun"),
    ("FRW", "Francistown Airport", "Francistown"),
    ("BBK", "Kasane Airport", "Kasane"),
    ("BOY", "Bobo Dioulasso Airport", "Bobo-Dioulasso"),
    ("OUA", "Ouagadougou Airport", "Ouagadougou"),
    ("BJM", "Bujumbura International Airport", "Bujumbura"),
    ("DLA", "Douala Airport", "Douala"),
    ("NSI", "Nsimalen Airport", "Yaoundé"),
    ("BVC", "Aristides Pereira International Airport", "Boa Vista Island"),
    ("SID", "Amílcar Cabral International Airport", "Sal Island"),
    ("RAI", "Nelson Mandela International Airport", "Praia, Santiago Island"),
    ("VXE", "Cesária Évora Airport", "Sao Vicente Island"),
    ("BGF", "M'Poko International Airport", "Bangui"),
    ("NDJ", "N'Djamena International Airport", "N'Djamena"),
    ("HAH", "Prince Said Ibrahim International Airport", "Moroni, Comoros"),
    ("ABJ", "Port Bouet Airport", "Abidjan"),
    ("GOM", "Goma International Airport", "Goma"),
    ("FIH", "N'djili Airport", "Kinshasa"),
    ("FKI", "Bangoka International Airport", "Kisangani"),
    ("FBM", "Lubumbashi International Airport", "Lubumbashi"),
    ("BZV", "Maya-Maya Airport", "Brazzaville"),
    ("PNR", "Pointe Noire Airport", "Pointe-Noire"),
    ("JIB", "Djibouti–Ambouli International Airport", "Djibouti City"),
    ("HBE", "Borg El Arab Airport", "Alexandria"),
    ("ALY", "Alexandria International Airport", "Alexandria"),
    ("ATZ", "Assiut Airport", "Asyut"),
    ("ASW", "Aswan International Airport", "Aswan"),
    ("CAI", "Cairo International Airport", "Cairo"),
    ("AAC", "El Arish International Airport", "El Arish"),
    ("DBB", "Al Alamain International Airport", "El Dabaa"),
    ("HRG", "Hurghada International Airport", "Hurghada"),
    ("LXR", "Luxor International Airport", "Luxor"),
    ("RMF", "Marsa Alam International Airport", "Marsa Alam"),
    ("MUH", "Mersa Matruh Airport", "Mersa Matruh"),
    ("SKV", "St. Catherine International Airport", "Saint Catherine"),
    ("SSH", "Sharm el-Sheikh International Airport", "Sharm el-Sheikh"),
    ("HMB", "Sohag International Airport", "Sohag"),
    ("TCP", "Taba International Airport", "Taba"),
    ("SSG", "Malabo International Airport", "Malabo"),
    ("ASM", "Asmara International Airport", "Asmara"),
    ("SHO", "King Mswati III International Airport", "Manzini"),
    ("ADD", "Addis Ababa Bole International Airport", "Addis Ababa"),
    ("DIR", "Aba Tenna Dejazmach Yilma International Airport", "Dire Dawa"),
    ("MVB", "M'Vengue El Hadj Omar Bongo Ondimba International Airport", "Franceville"),
    ("LBV", "Libreville International Airport", "Libreville"),
    ("POG", "Port-Gentil International Airport", "Port-Gentil"),
    ("BJL", "Banjul International Airport", "Banjul"),
    ("ACC", "Kotoka International Airport", "Accra"),
    ("TML", "Tamale Airport", "Tamale"),
    ("CKY", "Conakry International Airport", "Conakry"),
    ("OXB", "Osvaldo Vieira International Airport", "Bissau"),
    ("BQE", "Bubaque Airport", "Bubaque"),
    ("EDL", "Eldoret International Airport", "Eldoret"),
    ("MBA", "Moi International Airport", "Mombasa"),
    ("KIS", "Kisumu International Airport", "Kisumu"),
    ("NBO", "Jomo Kenyatta International Airport", "Nairobi"),
    ("MSU", "Moshoeshoe I International Airport", "Maseru"),
    ("ROB", "Roberts International Airport", "Monrovia"),
    ("BEN", "Benina International Airport", "Benghazi"),
    ("SEB", "Sebha Airport", "Sabha"),
    ("TIP", "Tripoli International Airport", "Tripoli"),
    ("MJI", "Mitiga International Airport", "Tajoura"),
    ("TNR", "Ivato International Airport", "Antananarivo"),
    ("DIE", "Arrachart Airport", "Antsiranana"),
    ("MJN", "Amborovy Airport", "Mahajanga"),
    ("NOS", "Fascene Airport", "Nosy Be"),
    ("TMM", "Toamasina Airport", "Toamasina"),
    ("FTU", "Tôlanaro Airport", "Tôlanaro"),
    ("TLE", "Toliara Airport", "Toliara"),
    ("BLZ", "Chileka International Airport", "Blantyre"),
    ("LLW", "Lilongwe International Airport", "Lilongwe"),
    ("BKO", "Senou International Airport", "Bamako"),
    ("NKC", "Nouakchott–Oumtounsy International Airport", "Nouakchott"),
    ("NDB", "Nouadhibou International Airport", "Nouadhibou"),
    ("MRU", "Sir Seewoosagur Ramgoolam International Airport", "Plaine Magnien"),
    ("DZA", "Dzaoudzi–Pamandzi International Airport", "Dzaoudzi"),
    ("AGA", "Al Massira Airport", "Agadir"),
    ("CMN", "Mohammed V International Airport", "Casablanca"),
    ("FEZ", "Fes-Saïss Airport", "Fes"),
    ("RAK", "Marrakech-Menara Airport", "Marrakech"),
    ("NDR", "Nador International Airport", "Nador"),
    ("OUD", "Angads Airport", "Oujda"),
    ("RBA", "Rabat-Salé Airport", "Rabat"),
    ("TNG", "Tangier-Boukhalef Airport", "Tangier"),
    ("TTU", "Sania Ramel Airport", "Tetouan"),
    ("VIL", "Dakhla Airport", "Dakhla"),
    ("EUN", "Hassan I Airport", "Laâyoune"),
    ("MPM", "Maputo International Airport", "Maputo"),
    ("BEW", "Beira Airport", "Beira"),
    ("INH", "Inhambane Airport", "Inhambane"),
    ("APL", "Nampula Airport", "Nampula"),
    ("POL", "Pemba Airport", "Pemba"),
    ("TET", "Chingozi Airport", "Tete"),
    ("VNX", "Vilankulo Airport", "Vilankulo"),
    ("WDH", "Hosea Kutako International Airport", "Windhoek"),
    ("WVB", "Walvis Bay Airport", "Walvis Bay"),
    ("NIM", "Diori Hamani International Airport", "Niamey"),
    ("ABV", "Nnamdi Azikiwe International Airport", "Abuja"),
    ("CBQ", "Margaret Ekpo International Airport", "Calabar"),
    ("ABB", "Asaba International Airport", "Asaba, Delta"),
    ("KAN", "Mallam Aminu Kano International Airport", "Kano"),
    ("LOS", "Murtala Mohammed International Airport", "Lagos"),
    ("PHC", "Port Harcourt International Airport", "Port Harcourt"),
    ("ENU", "Akanu Ibiam International Airport", "Enugu"),
    ("SKO", "Sadiq Abubakar III International Airport", "Sokoto"),
    ("RUN", "Roland Garros Airport", "Saint-Denis"),
    ("KGL", "Kigali International Airport", "Kigali"),
    ("HLE", "Saint Helena Airport", "Saint Helena"),
    ("TMS", "São Tomé International Airport", "São Tomé"),
    ("DKR", "Blaise Diagne International Airport", "Dakar"),
    ("SEZ", "Seychelles International Airport", "Victoria"),
    ("FNA", "Lungi International Airport", "Freetown"),
    ("BSA", "Bosaso Airport", "Bosaso"),
    ("GBY", "Abdullahi Yusuf Airport", "Galkayo"),
    ("GGR", "Garowe Airport", "Garowe"),
    ("HGA", "Hargeisa Airport", "Hargeisa"),
    ("KMU", "Kismayo Airport", "Kismayo"),
    ("MGQ", "Aden Adde International Airport", "Mogadishu"),
    ("CPT", "Cape Town International Airport", "Cape Town"),
    ("DUR", "King Shaka International Airport", "Durban"),
    ("JNB", "OR Tambo International Airport", "Johannesburg"),
    ("MQP", "Kruger Mpumalanga International Airport", "Nelspruit"),
    ("HLA", "Lanseria International Airport", "Johannesburg"),
    ("ELS", "East London Airport", "East London"),
    ("JUB", "Juba International Airport", "Juba"),
    ("KRT", "Khartoum International Airport", "Khartoum"),
    ("PZU", "Port Sudan New International Airport", "Port Sudan"),
    ("ARK", "Arusha Airport", "Arusha"),
    ("DAR", "Julius Nyerere International Airport", "Dar es Salaam"),
    ("JRO", "Kilimanjaro International Airport", "Hai District"),
    ("MWZ", "Mwanza Airport", "Mwanza"),
    ("ZNZ", "Abeid Amani Karume International Airport", "Unguja, Zanzibar"),
    ("LFW", "Tokoin Airport", "Lomé"),
    ("DJE", "Zarzis Airport", "Djerba"),
    ("NBE", "Enfidha-Hammamet International Airport", "Enfidha"),
    ("MIR", "Habib Bourguiba International Airport", "Monastir"),
    ("SFA", "Thyna International Airport", "Sfax"),
    ("TBJ", "Tabarka–Aïn Draham International Airport", "Tabarka"),
    ("TOE", "Nefta International Airport", "Tozeur"),
    ("TUN", "Carthage International Airport", "Tunis"),
    ("RUA", "Arua Airport", "Arua"),
    ("EBB", "Entebbe International Airport", "Entebbe"),
    ("ULU", "Gulu Airport", "Gulu"),
    ("LVI", "Harry Mwanga Nkumbula International Airport", "Livingstone"),
    ("LUN", "Kenneth Kaunda International Airport", "Lusaka"),
    ("NLA", "Simon Mwansa Kapwepwe International Airport", "Ndola"),
    ("HRE", "Robert Gabriel Mugabe International Airport", "Harare"),
    ("VFA", "Victoria Falls Airport", "Victoria Falls"),
    ("BUQ", "Joshua Mqabuko Nkomo International Airport", "Bulawayo"),
    ("AXA", "Clayton J. Lloyd International Airport", "The Valley"),
    ("ANU", "VC Bird International Airport", "Antigua"),
    ("AUA", "Queen Beatrix International Airport", "Oranjestad"),
    ("NAS", "Lynden Pindling International Airport", "Nassau"),
    ("CCZ", "Chub Cay International Airport", "Chub Cay"),
    ("GGT", "Exuma International Airport", "Exuma"),
    ("FPO", "Grand Bahama International Airport", "Freeport"),
    ("RSD", "Rock Sound International Airport", "South Eleuthera"),
    ("MHH", "Marsh Harbour International Airport", "Marsh Harbour"),
    ("BGI", "Grantley Adams International Airport", "Bridgetown"),
    ("EIS", "Terrance B. Lettsome International Airport", "Road Town"),
    ("BON", "Flamingo International Airport", "Kralendijk, Bonaire"),
    ("EUX", "F. D. Roosevelt Airport", "Oranjestad, Sint Eustatius"),
    ("SAB", "Juancho E. Yrausquin Airport", "Saba"),
    ("CYB", "Charles Kirkconnell International Airport", "Cayman Brac"),
    ("GCM", "Owen Roberts International Airport", "Georgetown"),
    ("CMW", "Ignacio Agramonte International Airport", "Camagüey"),
    ("CCC", "Jardines del Rey Airport", "Cayo Coco"),
    ("CYO", "Vilo Acuña Airport", "Cayo Largo del Sur"),
    ("CFG", "Jaime González Airport", "Cienfuegos"),
    ("HAV", "José Martí International Airport", "Havana"),
    ("HOG", "Frank País Airport", "Holguín"),
    ("SNU", "Abel Santa María Airport", "Santa Clara"),
    ("SCU", "Antonio Maceo Airport", "Santiago de Cuba"),
    ("VRA", "Juan Gualberto Gómez Airport", "Varadero"),
    ("CUR", "Hato International Airport", "Willemstad"),
    ("DOM", "Melville Hall Airport", "Roseau"),
    ("BRX", "María Montez International Airport", "Barahona"),
    ("LRM", "La Romana International Airport", "La Romana"),
    ("PUJ", "Punta Cana International Airport", "Punta Cana"),
    ("AZS", "Samaná El Catey International Airport", "Samana"),
    ("POP", "Gregorio Luperón International Airport", "San Felipe de Puerto Plata"),
    ("STI", "Cibao International Airport", "Santiago de los Caballeros"),
    ("SDQ", "Las Américas International Airport", "Santo Domingo"),
    ("GND", "Maurice Bishop International Airport", "Grenada"),
    ("PTP", "Pôle Caraïbes International Airport", "Pointe-à-Pitre"),
    ("CAP", "Cap-Haïtien International Airport", "Cap-Haïtien"),
    ("PAP", "Toussaint Louverture International Airport", "Port-au-Prince"),
    ("KIN", "Norman Manley International Airport", "Kingston"),
    ("MBJ", "Sangster International Airport", "Montego Bay"),
    ("FDF", "Martinique Aimé Césaire International Airport", "Fort-de-France"),
    ("MNI", "John A. Osborne Airport", "Brades"),
    ("BQN", "Rafael Hernández Airport", "Aguadilla"),
    ("SJU", "Luis Muñoz Marín International Airport", "San Juan"),
    ("SBH", "Gustaf III Airport", "St. Jean"),
    ("SKB", "Robert L. Bradshaw International Airport", "Saint Kitts"),
    ("UVF", "Hewanorra International Airport", "Vieux Fort Quarter"),
    ("SVD", "Argyle International Airport", "Kingstown"),
    ("CIW", "Canouan Airport", "Canouan"),
    ("SXM", "Princess Juliana International Airport", "Philipsburg"),
    ("POS", "Piarco International Airport", "Port of Spain"),
    ("TAB", "Arthur Napoleon Raymond Robinson International Airport (formerly Crown Point International Airport)", "Tobago"),
    ("PLS", "Providenciales Airport", "Providenciales"),
    ("STT", "Cyril E. King Airport", "Saint Thomas"),
    ("STX", "Henry E. Rohlsen Airport", "Saint Croix"),
    ("BZE", "Philip S. W. Goldson International Airport", "Belize City"),
    ("LIR", "Daniel Oduber Quirós International Airport", "Liberia"),
    ("SJO", "Juan Santamaría International Airport", "San José de Costa Rica"),
    ("SAL", "Monseñor Óscar Arnulfo Romero International Airport", "San Salvador"),
    ("FRS", "Mundo Maya International Airport", "Flores"),
    ("GUA", "La Aurora International Airport", "Guatemala City"),
    ("LCE", "Golosón International Airport", "La Ceiba"),
    ("RTB", "Juan Manuel Gálvez International Airport", "Roatán"),
    ("SAP", "Ramón Villeda Morales International Airport", "San Pedro Sula"),
    ("TGU", "Toncontin International Airport", "Tegucigalpa"),
    ("MGA", "Augusto C. Sandino International Airport", "Managua"),
    ("BEF", "Bluefields Airport", "Bluefields"),
    ("RNI", "Corn Island Airport", "Corn Island"),
    ("PUZ", "Puerto Cabezas Airport", "Puerto Cabezas"),
    ("BOC", "Bocas del Toro ""Isla Colón"" International Airport", "Bocas del Toro"),
    ("DAV", "Enrique Malek International Airport", "David, Chiriquí"),
    ("PTY", "Tocumen International Airport", "Panama City"),
    ("BDA", "L.F. Wade International Airport", "St. George's, Bermuda"),
    ("YYC", "Calgary International Airport", "Calgary"),
    ("YEG", "Edmonton International Airport", "Edmonton"),
    ("YXY", "Erik Nielsen Whitehorse International Airport", "Whitehorse"),
    ("YQX", "Gander International Airport", "Gander"),
    ("YHZ", "Halifax Stanfield International Airport", "Halifax (Goffs)"),
    ("YHM", "John C. Munro Hamilton International Airport", "Hamilton"),
    ("YLK", "Kelowna International Airport", "Kelowna"),
    ("YXU", "London International Airport", "London"),
    ("YQM", "Greater Moncton International Airport", "Moncton (Dieppe)"),
    ("YUL", "Montreal-Pierre Elliott Trudeau International Airport", "Montreal (Dorval)"),
    ("YOW", "Ottawa Macdonald-Cartier International Airport", "Ottawa"),
    ("YQB", "Quebec/Jean Lesage International Airport", "Quebec City"),
    ("YQR", "Regina International Airport", "Regina"),
    ("YXE", "Saskatoon John G. Diefenbaker International Airport", "Saskatoon"),
    ("YYT", "St. John's International Airport", "St. John's"),
    ("YYZ", "Toronto Pearson International Airport", "Mississauga / Toronto"),
    ("YVR", "Vancouver International Airport", "Vancouver (Richmond)"),
    ("YYJ", "Victoria International Airport", "Victoria"),
    ("YWG", "Winnipeg James Armstrong Richardson International Airport", "Winnipeg"),
    ("SFJ", "Kangerlussuaq Airport", "Kangerlussuaq"),
    ("GOH", "Nuuk Airport", "Nuuk"),
    ("JAV", "Ilulissat Airport", "Ilulissat"),
    ("UAK", "Narsarsuaq Airport", "Narsarsuaq"),
    ("ACA", "General Juan N. Alvarez International Airport", "Acapulco"),
    ("AGU", "Lic. Jesús Terán Peredo International Airport", "Aguascalientes"),
    ("CUN", "Cancun International Airport", "Cancún"),
    ("CUU", "Roberto Fierro Villalobos International Airport", "Chihuahua"),
    ("CME", "Ciudad del Carmen International Airport", "Ciudad del Carmen"),
    ("CZM", "Cozumel International Airport", "Cozumel"),
    ("CUL", "Federal de Bachigualato International Airport", "Culiacán"),
    ("DGO", "General Guadalupe Victoria International Airport", "Durango"),
    ("GDL", "Don Miguel Hidalgo y Costilla International Airport", "Guadalajara"),
    ("HMO", "Hermosillo International Airport", "Hermosillo"),
    ("HUX", "Bahías de Huatulco International Airport", "Huatulco"),
    ("ZIH", "Ixtapa-Zihuatanejo International Airport", "Ixtapa"),
    ("BJX", "Del Bajío International Airport", "León"),
    ("LTO", "Loreto International Airport", "Loreto"),
    ("SJD", "Los Cabos International Airport", "Los Cabos"),
    ("ZLO", "Playa de Oro International Airport", "Manzanillo"),
    ("MZT", "General Rafael Buelna International Airport", "Mazatlán"),
    ("MID", "Manuel Crescencio Rejón International Airport", "Mérida"),
    ("MEX", "Mexico City International Airport", "Mexico City"),
    ("MTY", "General Mariano Escobedo International Airport", "Monterrey"),
    ("MLM", "General Francisco J. Mujica International Airport", "Morelia"),
    ("OAX", "Xoxocotlán International Airport", "Oaxaca"),
    ("PBC", "Hermanos Serdán International Airport", "Puebla"),
    ("PVR", "Lic. Gustavo Díaz Ordaz International Airport", "Puerto Vallarta"),
    ("QRO", "Querétaro Intercontinental Airport", "Querétaro"),
    ("REX", "General Lucio Blanco International Airport", "Reynosa"),
    ("SLW", "Plan de Guadalupe International Airport", "Saltillo"),
    ("SLP", "Ponciano Arriaga International Airport", "San Luis Potosí"),
    ("TAM", "General Francisco Javier Mina International Airport", "Tampico"),
    ("TIJ", "Gral. Abelardo L. Rodríguez International Airport", "Tijuana"),
    ("TLC", "Lic. Adolfo López Mateos International Airport", "Toluca"),
    ("TRC", "Francisco Sarabia International Airport", "Torreón"),
    ("TGZ", "Angel Albino Corzo International Airport", "Tuxtla Gutierrez"),
    ("UPN", "Uruapan International Airport", "Uruapan"),
    ("VER", "General Heriberto Jara International Airport", "Veracruz"),
    ("VSA", "Carlos Rovirosa Pérez International Airport", "Villahermosa"),
    ("ZCL", "General Leobardo C. Ruiz International Airport", "Zacatecas"),
    ("FSP", "Saint-Pierre Airport", "Saint-Pierre"),
    ("AKC", "Akron Executive Airport", "Akron"),
    ("ALB", "Albany International Airport", "Albany"),
    ("ABQ", "Albuquerque International Sunport", "Albuquerque"),
    ("ANC", "Ted Stevens Anchorage International Airport", "Anchorage"),
    ("ATW", "Appleton International Airport", "Appleton"),
    ("ATL", "Hartsfield-Jackson Atlanta International Airport", "Atlanta"),
    ("ACY", "Atlantic City International Airport", "Atlantic City"),
    ("AUS", "Austin-Bergstrom International Airport", "Austin"),
    ("BWI", "Baltimore-Washington International Thurgood Marshall Airport", "Baltimore"),
    ("BGR", "Bangor International Airport", "Bangor"),
    ("BHM", "Birmingham-Shuttlesworth International Airport", "Birmingham"),
    ("BOI", "Boise Airport", "Boise"),
    ("BOS", "Logan International Airport", "Boston"),
    ("BUF", "Buffalo Niagara International Airport", "Buffalo"),
    ("CLT", "Charlotte/Douglas International Airport", "Charlotte"),
    ("CHS", "Charleston International Airport", "Charleston (SC)"),
    ("MDW", "Chicago Midway International Airport", "Chicago"),
    ("ORD", "O'Hare International Airport", "Chicago"),
    ("CVG", "Cincinnati/Northern Kentucky International Airport", "Cincinnati"),
    ("CLE", "Cleveland Hopkins International Airport", "Cleveland"),
    ("CMH", "John Glenn Columbus International Airport", "Columbus (OH)"),
    ("LCK", "Rickenbacker International Airport", "Columbus (OH)"),
    ("DFW", "Dallas/Fort Worth International Airport", "Dallas"),
    ("DAY", "Dayton International Airport", "Dayton (OH)"),
    ("DEN", "Denver International Airport", "Denver"),
    ("DSM", "Des Moines International Airport", "Des Moines (IA)"),
    ("DTW", "Detroit Metropolitan Wayne County Airport", "Detroit"),
    ("ELP", "El Paso International Airport", "El Paso"),
    ("FAI", "Fairbanks International Airport", "Fairbanks"),
    ("FLL", "Fort Lauderdale-Hollywood International Airport", "Fort Lauderdale"),
    ("RSW", "Southwest Florida International Airport", "Fort Myers"),
    ("FAT", "Fresno Yosemite International Airport", "Fresno"),
    ("BDL", "Bradley International Airport", "Hartford"),
    ("GRR", "Gerald R. Ford International Airport", "Grand Rapids"),
    ("GRB", "Green Bay–Austin Straubel International Airport", "Green Bay"),
    ("GSO", "Piedmont Triad International Airport", "Greensboro"),
    ("ITO", "Hilo International Airport", "Hilo"),
    ("HNL", "Daniel K. Inouye International Airport", "Honolulu"),
    ("IAH", "George Bush Intercontinental Airport", "Houston"),
    ("HOU", "William P. Hobby Airport", "Houston"),
    ("HSV", "Huntsville International Airport", "Huntsville (AL)"),
    ("IND", "Indianapolis International Airport", "Indianapolis"),
    ("JAX", "Jacksonville International Airport", "Jacksonville"),
    ("JNU", "Juneau International Airport", "Juneau"),
    ("MCI", "Kansas City International Airport", "Kansas City"),
    ("KTN", "Ketchikan International Airport", "Ketchikan"),
    ("EYW", "Key West International Airport", "Key West"),
    ("KOA", "Kona International Airport", "Kona"),
    ("TYS", "McGhee Tyson Airport", "Knoxville"),
    ("LAL", "Lakeland Linder International Airport", "Lakeland"),
    ("LAN", "Capital Region International Airport", "Lansing"),
    ("LAS", "McCarran International Airport", "Las Vegas"),
    ("LIT", "Clinton National Airport", "Little Rock"),
    ("LAX", "Los Angeles International Airport", "Los Angeles"),
    ("SDF", "Louisville International Airport", "Louisville"),
    ("MLB", "Melbourne International Airport", "Melbourne (FL)"),
    ("MEM", "Memphis International Airport", "Memphis"),
    ("MIA", "Miami International Airport", "Miami"),
    ("MAF", "Midland International Air & Space Port", "Midland"),
    ("MKE", "General Mitchell International Airport", "Milwaukee"),
    ("MSP", "Minneapolis-Saint Paul International Airport", "Minneapolis/St. Paul"),
    ("MYR", "Myrtle Beach International Airport", "Myrtle Beach"),
    ("BNA", "Nashville International Airport", "Nashville"),
    ("MSY", "Louis Armstrong New Orleans International Airport", "New Orleans"),
    ("JFK", "John F. Kennedy International Airport", "New York City"),
    ("LGA", "LaGuardia Airport", "New York City"),
    ("EWR", "Newark Liberty International Airport", "Newark"),
    ("SWF", "Stewart International Airport", "Newburgh"),
    ("ORF", "Norfolk International Airport", "Norfolk (VA)"),
    ("OAK", "Metropolitan Oakland International Airport", "Oakland"),
    ("OKC", "Will Rogers World Airport", "Oklahoma City"),
    ("OMA", "Eppley Airfield", "Omaha"),
    ("ONT", "Ontario International Airport", "Ontario"),
    ("SNA", "John Wayne Airport", "Orange County"),
    ("MCO", "Orlando International Airport", "Orlando"),
    ("SFB", "Orlando Sanford International Airport", "Orlando/Sanford"),
    ("PSP", "Palm Springs International Airport", "Palm Springs"),
    ("ECP", "Northwest Florida Beaches International Airport", "Panama City"),
    ("PNS", "Pensacola International Airport", "Pensacola"),
    ("PHL", "Philadelphia International Airport", "Philadelphia"),
    ("PHX", "Phoenix Sky Harbor International Airport", "Phoenix"),
    ("AZA", "Phoenix–Mesa Gateway Airport", "Phoenix/Mesa"),
    ("PIT", "Pittsburgh International Airport", "Pittsburgh"),
    ("PWM", "Portland International Jetport", "Portland (ME)"),
    ("PDX", "Portland International Airport", "Portland (OR)"),
    ("PVD", "T.F. Green Airport", "Providence"),
    ("RAC", "Batten International Airport", "Racine"),
    ("RDU", "Raleigh-Durham International Airport", "Raleigh/Durham"),
    ("RNO", "Reno-Tahoe International Airport", "Reno"),
    ("RIC", "Richmond International Airport", "Richmond"),
    ("RST", "Rochester International Airport", "Rochester (MN)"),
    ("ROC", "Greater Rochester International Airport", "Rochester (NY)"),
    ("RFD", "Chicago Rockford International Airport", "Rockford"),
    ("SMF", "Sacramento International Airport", "Sacramento"),
    ("SLC", "Salt Lake City International Airport", "Salt Lake City"),
    ("SAT", "San Antonio International Airport", "San Antonio"),
    ("SBD", "San Bernardino International Airport", "San Bernardino"),
    ("SAN", "San Diego International Airport", "San Diego"),
    ("SFO", "San Francisco International Airport", "San Francisco"),
    ("SJC", "San Jose International Airport", "San Jose (CA)"),
    ("SRQ", "Sarasota-Bradenton International Airport", "Sarasota/Bradenton"),
    ("SAV", "Savannah/Hilton Head International Airport", "Savannah (GA)/Hilton Head (SC)"),
    ("LKE", "Kenmore Air Harbor Seaplane Base", "Seattle"),
    ("BFI", "King County International Airport", "Seattle"),
    ("SEA", "Seattle-Tacoma International Airport", "Seattle"),
    ("PAE", "Paine Field", "Snohomish County (WA)"),
    ("GEG", "Spokane International Airport", "Spokane"),
    ("STL", "St. Louis Lambert International Airport", "St. Louis"),
    ("PIE", "St. Petersburg-Clearwater International Airport", "St. Petersburg (FL)"),
    ("SYR", "Syracuse Hancock International Airport", "Syracuse"),
    ("TLH", "Tallahassee International Airport", "Tallahassee"),
    ("TPA", "Tampa International Airport", "Tampa"),
    ("DCA", "Ronald Reagan Washington National Airport**", "Washington, D.C."),
    ("IAD", "Washington Dulles International Airport", "Washington, D.C."),
    ("PBI", "Palm Beach International Airport", "West Palm Beach"),
    ("AVP", "Wilkes-Barre/Scranton International Airport", "Wilkes-Barre/Scranton"),
    ("ILM", "Wilmington International Airport", "Wilmington (NC)"),
    ("EZE", "Ministro Pistarini International Airport", "Buenos Aires"),
    ("AEP", "Aeroparque Jorge Newbery", "Buenos Aires"),
    ("COR", "Ingeniero Ambrosio L.V. Taravella International Airport", "Córdoba"),
    ("MDZ", "Governor Francisco Gabrielli International Airport", "Mendoza"),
    ("IGR", "Cataratas del Iguazú International Airport", "Puerto Iguazú"),
    ("RES", "Resistencia International Airport", "Resistencia"),
    ("RGL", "Piloto Civil N. Fernández International Airport", "Río Gallegos"),
    ("BRC", "Teniente Luis Candelaria International Airport", "San Carlos de Bariloche"),
    ("USH", "Ushuaia International Airport", "Ushuaia"),
    ("LPB", "El Alto International Airport", "La Paz"),
    ("VVI", "Viru Viru International Airport", "Santa Cruz de la Sierra"),
    ("CBB", "Jorge Wilstermann International Airport", "Cochabamba"),
    ("AJU", "Santa Maria Airport", "Aracaju"),
    ("BEL", "Val de Cães International Airport", "Belém"),
    ("CNF", "Tancredo Neves International Airport", "Belo Horizonte"),
    ("BVB", "Boa Vista International Airport", "Boa Vista"),
    ("BSB", "Brasília International Airport", "Brasília"),
    ("VCP", "Viracopos International Airport", "Campinas"),
    ("CGR", "Campo Grande International Airport", "Campo Grande"),
    ("CGB", "Marechal Rondon International Airport", "Cuiabá"),
    ("CWB", "Afonso Pena International Airport", "Curitiba"),
    ("FLN", "Hercílio Luz International Airport", "Florianópolis"),
    ("FOR", "Pinto Martins International Airport", "Fortaleza"),
    ("IGU", "Cataratas International Airport", "Foz do Iguaçu"),
    ("GYN", "Santa Genoveva Airport", "Goiânia"),
    ("JPA", "Presidente Castro Pinto International Airport", "João Pessoa"),
    ("MCZ", "Zumbi dos Palmares International Airport", "Maceió"),
    ("MAO", "Eduardo Gomes International Airport", "Manaus"),
    ("NAT", "Greater Natal International Airport", "Natal"),
    ("PNZ", "Senador Nilo Coelho Airport", "Petrolina"),
    ("POA", "Salgado Filho International Airport", "Porto Alegre"),
    ("PVH", "Governador Jorge Teixeira de Oliveira International Airport", "Porto Velho"),
    ("REC", "Guararapes International Airport", "Recife"),
    ("RBR", "Rio Branco International Airport", "Rio Branco"),
    ("GIG", "Rio de Janeiro–Galeão International Airport", "Rio de Janeiro"),
    ("SDU", "Santos Dumont Airport", "Rio de Janeiro"),
    ("SSA", "Deputado Luís Eduardo Magalhães International Airport", "Salvador"),
    ("SLZ", "Marechal Cunha Machado International Airport", "São Luís"),
    ("CGH", "São Paulo–Congonhas Airport", "São Paulo"),
    ("GRU", "São Paulo–Guarulhos International Airport", "São Paulo"),
    ("THE", "Teresina Airport", "Teresina"),
    ("UDI", "Uberlândia Airport", "Uberlândia"),
    ("VIX", "Eurico de Aguiar Salles Airport", "Vitória"),
    ("ANF", "Cerro Moreno International Airport", "Antofagasta"),
    ("CCP", "Carriel Sur International Airport", "Concepción"),
    ("PMC", "El Tepual International Airport", "Puerto Montt"),
    ("PUQ", "Presidente Carlos Ibáñez del Campo International Airport", "Punta Arenas"),
    ("SCL", "Comodoro Arturo Merino Benítez International Airport", "Santiago de Chile"),
    ("AXM", "El Edén International Airport", "Armenia"),
    ("BAQ", "Ernesto Cortissoz International Airport", "Barranquilla"),
    ("BOG", "El Dorado International Airport", "Bogotá"),
    ("BGA", "Palonegro International Airport", "Bucaramanga"),
    ("BUN", " Gerardo Tobar López International Airport", "Buenaventura"),
    ("CLO", "Alfonso Bonilla Aragon International Airport", "Cali"),
    ("CTG", "Rafael Núñez International Airport", "Cartagena de Indias"),
    ("CUC", "Camilo Daza International Airport", "Cúcuta"),
    ("IBE", "Perales International Airport", "Ibagué"),
    ("IPI", "St. Louis-Ipiales International Airport", "Ipiales"),
    ("FLA", " Gustavo Artunduaga Paredes International Airport", "Florencia"),
    ("LET", "Alfredo Vásquez Cobo International Airport", "Leticia"),
    ("MCJ", "Jorge Isaacs Airport", "Maicao"),
    ("MZL", "La Nubia International Airport", "Manizales"),
    ("MDE", "José María Córdova International Airport", "Medellín"),
    ("MVP", "Fabio Alberto León Bentley Airport", "Mitú"),
    ("MTR", "Los Garzones International Airport", "Montería"),
    ("NVA", "Benito Salas International Airport", "Neiva"),
    ("PSO", "Antonio Nariño International Airport", "Pasto"),
    ("PEI", "Matecaña International Airport", "Pereira"),
    ("PPN", " Guillermo León Valencia International Airport", "Popayán"),
    ("PVA", "El Embrujo Airport", "Providence Island"),
    ("UIB", "El Caraño Airport", "Quibdó"),
    ("RCH", "Almirante Padilla Airport", "Riohacha"),
    ("ADZ", "Gustavo Rojas Pinilla International Airport", "San Andrés"),
    ("TLU", "Morrosquillo Gulf International Airport", "Tolú"),
    ("TCO", "La Florida International Airport", "Tumaco"),
    ("SMR", "Simón Bolívar International Airport", "Santa Marta"),
    ("CZU", "Las Brujas Airport", "Sincelejo"),
    ("VUP", " Alfonso López Pumarejo International Airport", "Valledupar"),
    ("VVC", "La Vanguardia International Airport", "Villavicencio"),
    ("EYP", "El Alcaraván International Airport", "Yopal"),
    ("CUE", "Mariscal Lamar International Airport", "Cuenca"),
    ("ESM", "Carlos Concha Torres International Airport", "Esmeraldas"),
    ("GYE", "José Joaquín de Olmedo International Airport", "Guayaquil"),
    ("ETR", "Santa Rosa International Airport", "Machala"),
    ("MEC", "Eloy Alfaro International Airport", "Manta"),
    ("UIO", "Mariscal Sucre International Airport", "Quito"),
    ("TUA", "Teniente Coronel Luis a Mantilla International Airport", "Tulcán"),
    ("MPN", "RAF Mount Pleasant", "Mount Pleasant"),
    ("CAY", "Cayenne-Rochambeau Airport", "Cayenne"),
    ("GEO", "Cheddi Jagan International Airport", "Georgetown"),
    ("ASU", "Silvio Pettirossi International Airport", "Asunción"),
    ("AGT", "Guaraní International Airport", "Ciudad del Este"),
    ("AQP", "Rodríguez Ballón International Airport", "Arequipa"),
    ("CUZ", "Alejandro Velasco Astete International Airport", "Cusco"),
    ("LIM", "Jorge Chávez International Airport", "Lima"),
    ("PBM", "Johan Adolf Pengel International Airport", "Paramaribo"),
    ("MVD", "Carrasco International Airport", "Montevideo"),
    ("PDP", "Capitan Corbeta CA Curbelo International Airport", "Punta del Este"),
    ("RVY", "Rivera International Airport", "Rivera"),
    ("CCS", "Simón Bolívar International Airport", "Caracas"),
    ("MAR", "La Chinita International Airport", "Maracaibo"),
    ("VLN", "Arturo Michelena International Airport", "Valencia"),
    ("SCO", "Aktau Airport", "Aktau"),
    ("AKX", "Aktobe International Airport", "Aktobe"),
    ("ALA", "Almaty International Airport", "Almaty"),
    ("GUW", "Atyrau Airport", "Atyrau"),
    ("KGF", "Karaganda Airport", "Karaganda"),
    ("KOV", "Kokshetau Airport", "Kokshetau"),
    ("KSN", "Kostanay Airport", "Kostanay"),
    ("KZO", "Kyzylorda Airport", "Kyzylorda"),
    ("TSE", "Nursultan Nazarbayev International Airport", "Nur-Sultan"),
    ("URA", "Oral Ak Zhol Airport", "Oral"),
    ("UKK", "Oskemen Airport", "Oskemen"),
    ("PWQ", "Pavlodar Airport", "Pavlodar"),
    ("PPK", "Petropavl Airport", "Petropavl"),
    ("PLX", "Semey Airport", "Semey"),
    ("CIT", "Shymkent Airport", "Shymkent"),
    ("DMB", "Taraz Airport", "Taraz"),
    ("FRU", "Manas Airport", "Bishkek"),
    ("IKU", "Issyk-Kul International Airport", "Issyk-Kul"),
    ("КПЖ", "Karakol International Airport", "Karakol"),
    ("OSS", "Osh Airport", "Osh"),
    ("KQT", "Bokhtar International Airport", "Bokhtar"),
    ("DYU", "Dushanbe Airport", "Dushanbe"),
    ("LBD", "Khujand Airport", "Khujand"),
    ("TJU", "Kulob Airport", "Kulob"),
    ("ASB", "Ashgabat Airport", "Ashgabat"),
    ("TAZ", "Daşoguz Airport", "Daşoguz"),
    ("MYP", "Mary International Airport", "Mary"),
    ("KRW", "Turkmenbashi International Airport", "Turkmenbashi"),
    ("CRZ", "Turkmenabat International Airport", "Türkmenabat"),
    ("AZN", "Andizhan Airport", "Andijan"),
    ("BHK", "Bukhara International Airport", "Bukhara"),
    ("FEG", "Fergana International Airport", "Fergana"),
    ("KSQ", "Karshi Airport", "Qarshi"),
    ("NMA", "Namangan Airport", "Namangan"),
    ("NVI", "Navoi International Airport", "Navoi"),
    ("NCU", "Nukus Airport", "Nukus"),
    ("SKD", "Samarkand International Airport", "Samarkand"),
    ("TAS", "Tashkent International Airport", "Tashkent"),
    ("TMJ", "Termez Airport", "Termez"),
    ("UGC", "Urgench International Airport", "Urgench"),
    ("FNJ", "Pyongyang International Airport", "Pyongyang"),
    ("AXT", "Akita Airport", "Akita"),
    ("AOJ", "Aomori Airport", "Aomori"),
    ("FUK", "Fukuoka Airport", "Fukuoka"),
    ("HKD", "Hakodate Airport", "Hakodate"),
    ("KOJ", "Kagoshima Airport", "Kagoshima"),
    ("KMQ", "Komatsu Airport", "Komatsu"),
    ("HIJ", "Hiroshima Airport", "Hiroshima"),
    ("KKJ", "New Kitakyushu Airport", "Kitakyushu"),
    ("NGS", "Nagasaki Airport", "Nagasaki"),
    ("OKA", "Naha Airport", "Naha"),
    ("NGO", "Chubu Centrair International Airport", "Nagoya"),
    ("KIJ", "Niigata Airport", "Niigata"),
    ("OIT", "Oita Airport", "Oita"),
    ("OKJ", "Okayama Airport", "Okayama"),
    ("KIX", "Kansai International Airport", "Osaka"),
    ("CTS", "New Chitose Airport", "Sapporo"),
    ("SDJ", "Sendai Airport", "Sendai"),
    ("FSZ", "Shizuoka Airport", "Shizuoka"),
    ("HND", "Haneda International Airport", "Tokyo/Yokohama"),
    ("NRT", "Narita International Airport", "Tokyo/Chiba"),
    ("ULN", "Buyant-Ukhaa International Airport", "Ulan Bator"),
    ("BAV", "Baotou Airport", "Baotou"),
    ("BHY", "Beihai Fucheng Airport", "Beihai"),
    ("PEK", "Beijing Capital International Airport", "Beijing"),
    ("PKX", "Beijing Daxing International Airport", "Beijing"),
    ("CGQ", "Changchun Longjia International Airport", "Changchun"),
    ("CSX", "Changsha Huanghua International Airport", "Changsha"),
    ("CZX", "Changzhou Benniu Airport", "Changzhou"),
    ("CTU", "Chengdu Shuangliu International Airport", "Chengdu"),
    ("CKG", "Chongqing Jiangbei International Airport", "Chongqing"),
    ("DLC", "Dalian Zhoushuizi International Airport", "Dalian"),
    ("DDG", "Dandong Langtou Airport", "Dandong"),
    ("DAT", "Datong Yungang Airport", "Datong"),
    ("DNH", "Dunhuang Airport", "Dunhuang"),
    ("ENH", "Enshi Xujiaping Airport", "Enshi City"),
    ("FOC", "Fuzhou Changle International Airport", "Fuzhou"),
    ("KOW", "Ganzhou Huangjin Airport", "Ganzhou"),
    ("CAN", "Guangzhou Baiyun International Airport", "Guangzhou"),
    ("KWL", "Guilin Liangjiang International Airport", "Guilin"),
    ("KWE", "Guiyang Longdongbao Airport", "Guiyang"),
    ("HAK", "Haikou Meilan International Airport", "Haikou"),
    ("HGH", "Hangzhou Xiaoshan International Airport", "Hangzhou"),
    ("HRB", "Harbin Taiping International Airport", "Harbin"),
    ("HFE", "Hefei Xinqiao International Airport", "Hefei"),
    ("HET", "Hohhot Airport", "Hohhot"),
    ("HIA", "Huai'an Lianshui Airport", "Huai'an"),
    ("TXN", "Huangshan Tunxi International Airport", "Huangshan City"),
    ("HLD", "Hulunbuir Hailar Airport", "Hulunbuir"),
    ("JMU", "Jiamusi Dongjiao Airport", "Jiamusi"),
    ("SWA", "Jieyang Chaoshan International Airport", "Jieyang"),
    ("TNA", "Jinan Yaoqiang International Airport", "Jinan"),
    ("KMG", "Kunming Changshui International Airport", "Kunming"),
    ("LHW", "Lanzhou Zhongchuan International Airport", "Lanzhou"),
    ("LXA", "Lhasa Gonggar Airport", "Lhasa"),
    ("LYG", "Lianyungang Baitabu Airport", "Lianyungang"),
    ("LJG", "Lijiang Sanyi International Airport", "Lijiang"),
    ("LYI", "Linyi Qiyang Airport", "Linyi"),
    ("LYA", "Luoyang Beijiao Airport", "Luoyang"),
    ("LUM", "Dehong Mangshi Airport", "Mangshi"),
    ("NZH", "Manzhouli Airport", "Manzhouli"),
    ("MXZ", "Meixian Airport", "Meizhou"),
    ("MDG", "Mudanjiang Airport", "Mudanjiang"),
    ("KHN", "Nanchang Changbei International Airport", "Nanchang"),
    ("NKG", "Nanjing Lukou International Airport", "Nanjing"),
    ("NNG", "Nanning Wuxu International Airport", "Nanning"),
    ("NTG", "Nantong Xingdong Airport", "Nantong"),
    ("NGB", "Ningbo Lishe International Airport", "Ningbo"),
    ("DSN", "Ordos Ejin Horo Airport", "Ordos City"),
    ("TAO", "Qingdao liuting International Airport", "Qingdao"),
    ("BPE", "Qinhuangdao Beidaihe Airport", "Qinhuangdao"),
    ("NDG", "Qiqihar Sanjiazi Airport", "Qiqihar"),
    ("JJN", "Quanzhou Jinjiang International Airport", "Quanzhou"),
    ("SYX", "Sanya Phoenix International Airport", "Sanya"),
    ("SHA", "Shanghai Hongqiao International Airport", "Shanghai"),
    ("PVG", "Shanghai Pudong International Airport", "Shanghai"),
    ("SHE", "Shenyang Taoxian International Airport", "Shenyang"),
    ("SZX", "Shenzhen Bao'an International Airport", "Shenzhen"),
    ("SJW", "Shijiazhuang Zhengding International Airport", "Shijiazhuang"),
    ("TYN", "Taiyuan Wusu International Airport", "Taiyuan"),
    ("TSN", "Tianjin Binhai International Airport", "Tianjin"),
    ("UCB", "Ulanqab Airport", "Ulanqab"),
    ("URC", "Ürümqi Diwopu International Airport", "Ürümqi"),
    ("WXN", "Wanzhou Wuqiao Airport", "Wanzhou"),
    ("WEH", "Weihai International Airport", "Weihai"),
    ("WNZ", "Wenzhou Yongqiang Airport", "Wenzhou"),
    ("WUH", "Wuhan Tianhe International Airport", "Wuhan"),
    ("WUX", "Sunan Shuofang International Airport", "Wuxi"),
    ("WUS", "Wuyishan Airport", "Wuyishan"),
    ("XMN", "Xiamen Gaoqi International Airport", "Xiamen"),
    ("XIY", "Xi'an Xianyang International Airport", "Xi'an"),
    ("XNN", "Xining Caojiabao Airport", "Xining"),
    ("WUT", "Xinzhou Wutaishan Airport", "Xinzhou"),
    ("JHG", "Xishuangbanna Gasa International Airport", "Xishuangbanna"),
    ("XUZ", "Xuzhou Guanyin Airport", "Xuzhou"),
    ("YNZ", "Yancheng Nanyang Airport", "Yancheng"),
    ("YTY", "Yangzhou Taizhou International Airport", "Yangzhou"),
    ("YNJ", "Yanji Airport", "Yanji"),
    ("YNT", "Yantai Penglai International Airport", "Yantai"),
    ("YIH", "Yichang Sanxia Airport", "Yichang"),
    ("INC", "Yinchuan Hedong International Airport", "Yinchuan"),
    ("YIW", "Yiwu Airport", "Yiwu"),
    ("YCU", "Yuncheng Guangong Airport", "Yuncheng"),
    ("DYG", "Zhangjiajie Hehua Airport", "Zhangjiajie"),
    ("ZHA", "Zhanjiang Airport", "Zhanjiang"),
    ("CGO", "Zhengzhou Xinzheng International Airport", "Zhengzhou"),
    ("ZUH", "Zhuhai Jinwan Airport", "Zhuhai"),
    ("ZYI", "Zunyi Xinzhou Airport", "Zunyi"),
    ("HKG", "Hong Kong International Airport", "Hong Kong"),
    ("MFM", "Macau International Airport", "Macau"),
    ("HUN", "Hualien Airport", "Hualien"),
    ("KHH", "Kaohsiung International Airport", "Kaohsiung"),
    ("RMQ", "Taichung International Airport", "Taichung"),
    ("TNN", "Tainan Airport", "Tainan"),
    ("TSA", "Taipei Songshan Airport", "Taipei"),
    ("TPE", "Taoyuan International Airport", "Taoyuan"),
    ("PUS", "Gimhae International Airport", "Busan"),
    ("TAE", "Daegu International Airport", "Daegu"),
    ("CJU", "Jeju International Airport", "Jeju"),
    ("GMP", "Gimpo International Airport", "Seoul"),
    ("ICN", "Incheon International Airport", "Incheon"),
    ("CJJ", "Cheongju International Airport", "Cheongju"),
    ("MWX", "Muan International Airport", "Muan"),
    ("YNY", "Yangyang International Airport", "Yangyang"),
    ("CGP", "Shah Amanat International Airport", "Chittagong"),
    ("DAC", "Hazrat Shahjalal International Airport", "Dhaka"),
    ("ZYL", "Osmani International Airport", "Sylhet"),
    ("PBH", "Paro Airport", "Paro"),
    ("IXA", "Maharaja Bir Bikram Airport", "Agartala"),
    ("AMD", "Sardar Vallabhbhai Patel International Airport", "Ahmedabad"),
    ("ATQ", "Sri Guru Ram Dass Jee International Airport", "Amritsar"),
    ("IXU", "Aurangabad Airport", "Aurangabad"),
    ("BLR", "Kempegowda International Airport", "Bangalore"),
    ("BHO", "Raja Bhoj International Airport", "Bhopal"),
    ("BBI", "Biju Patnaik International Airport", "Bhubaneswar"),
    ("IXC", "Chandigarh International Airport", "Chandigarh"),
    ("MAA", "Chennai International Airport", "Chennai"),
    ("COK", "Cochin International Airport", "Cochin"),
    ("CJB", "Coimbatore International Airport", "Coimbatore"),
    ("DEL", "Indira Gandhi International Airport", "Delhi"),
    ("GOI", "Goa International Airport", "Goa"),
    ("GAY", "Gaya International Airport", "Gaya"),
    ("GAU", "Lokpriya Gopinath Bordoloi International Airport", "Guwahati"),
    ("HYD", "Rajiv Gandhi International Airport", "Hyderabad"),
    ("IMF", "Imphal International Airport", "Imphal"),
    ("IDR", "Devi Ahilya Bai Holkar International Airport", "Indore"),
    ("JAI", "Jaipur International Airport", "Jaipur"),
    ("CNN", "Kannur International Airport", "Kannur"),
    ("CCU", "Netaji Subhash Chandra Bose International Airport", "Kolkata"),
    ("CCJ", "Calicut International Airport", "Kozhikode"),
    ("LKO", "Chaudhary Charan Singh International Airport", "Lucknow"),
    ("IXM", "Madurai International Airport", "Madurai"),
    ("IXE", "Mangalore International Airport", "Mangalore"),
    ("BOM", "Chhatrapati Shivaji International Airport", "Mumbai"),
    ("NAG", "Dr. Babasaheb Ambedkar International Airport", "Nagpur"),
    ("PNQ", "Pune International Airport", "Pune"),
    ("IXB", "Bagdogra International Airport", "Siliguri"),
    ("SXR", "Srinagar Airport", "Srinagar"),
    ("STV", "Surat International Airport", "Surat"),
    ("TRZ", "Tiruchirappalli International Airport", "Trichy"),
    ("TRV", "Trivandrum International Airport", "Trivandrum"),
    ("VNS", "Lal Bahadur Shastri International Airport", "Varanasi"),
    ("VTZ", "Visakhapatnam Airport", "Visakhapatnam"),
    ("MLE", "Velana International Airport", "Hulhule Island"),
    ("GAN", "Gan International Airport", "Addu City"),
    ("HAQ", "Hanimaadhoo International Airport", "Hanimaadhoo"),
    ("KTM", "Tribhuvan International Airport", "Kathmandu"),
    ("BHV", "Bahawalpur Airport", "Bahawalpur"),
    ("LYP", "Faisalabad International Airport", "Faisalabad"),
    ("GWD", "Gwadar International Airport", "Gwadar"),
    ("ISB", "Islamabad International Airport", "Islamabad"),
    ("KHI", "Jinnah International Airport", "Karachi"),
    ("LHE", "Allama Iqbal International Airport", "Lahore"),
    ("MUX", "Multan International Airport", "Multan"),
    ("PEW", "Bacha Khan International Airport", "Peshawar"),
    ("UET", "Quetta International Airport", "Quetta"),
    ("RYK", "Shaikh Zayed International Airport", "Rahim Yar Khan"),
    ("SKT", "Sialkot International Airport", "Sialkot"),
    ("TUK", "Turbat International Airport", "Turbat"),
    ("CMB", "Bandaranaike International Airport", "Colombo"),
    ("HRI", "Mattala Rajapaksa International Airport", "Hambantota"),
    ("RML", "Ratmalana International Airport", "Colombo"),
    ("JAF", "Jaffna International Airport", "Jaffna"),
    ("BWN", "Brunei International Airport", "Bandar Seri Begawan"),
    ("PNH", "Phnom Penh International Airport", "Phnom Penh"),
    ("REP", "Siem Reap International Airport", "Siem Reap"),
    ("KOS", "Sihanouk International Airport", "Sihanoukville"),
    ("DIL", "Presidente Nicolau Lobato International Airport", "Dili"),
    ("BPN", "Sultan Aji Muhammad Sulaiman Airport", "Balikpapan"),
    ("BTJ", "Sultan Iskandar Muda International Airport", "Banda Aceh"),
    ("TKG", "Radin Inten II International Airport", "Bandar Lampung"),
    ("BDO", "Husein Sastranegara International Airport", "Bandung"),
    ("KJT", "Kertajati International Airport", "Bandung"),
    ("BDJ", "Syamsudin Noor International Airport", "Banjarmasin"),
    ("BWX", "Banyuwangi International Airport", "Banyuwangi"),
    ("BTH", "Hang Nadim International Airport", "Batam"),
    ("BIK", "Frans Kaisiepo International Airport", "Biak"),
    ("DPS", "Ngurah Rai International Airport", "Denpasar"),
    ("HLP", "Halim Perdanakusuma International Airport", "Jakarta"),
    ("CGK", "Soekarno Hatta International Airport", "Jakarta"),
    ("KOE", "El Tari International Airport", "Kupang"),
    ("UPG", "Sultan Hasanuddin International Airport", "Makassar"),
    ("MDC", "Sam Ratulangi International Airport", "Manado"),
    ("LOP", "Zainuddin Abdul Madjid International Airport", "Mataram"),
    ("KNO", "Kualanamu International Airport", "Medan"),
    ("PDG", "Minangkabau International Airport", "Padang"),
    ("PLM", "Sultan Mahmud Badaruddin II Airport", "Palembang"),
    ("PKU", "Sultan Syarif Qasim II International Airport", "Pekanbaru"),
    ("PNK", "Supadio International Airport", "Pontianak"),
    ("SRG", "Ahmad Yani International Airport", "Semarang"),
    ("DTB", "Sisingamangaraja XII International Airport", "Siborong-Borong"),
    ("SUB", "Juanda International Airport", "Surabaya"),
    ("SOC", "Adisumarmo International Airport", "Surakarta"),
    ("TJQ", "H.A.S. Hanandjoeddin International Airport", "Tanjung Pandan"),
    ("TRK", "Juwata International Airport", "Tarakan"),
    ("YIA", "Yogyakarta International Airport", "Yogyakarta"),
    ("LPQ", "Luang Prabang International Airport", "Luang Prabang"),
    ("PKZ", "Pakse International Airport", "Pakse"),
    ("ZVK", "Savannakhet Airport", "Savannakhet"),
    ("VTE", "Wattay International Airport", "Vientiane"),
    ("AOR", "Sultan Abdul Halim Airport", "Alor Setar"),
    ("IPH", "Sultan Azlan Shah Airport", "Ipoh"),
    ("JHB", "Senai International Airport", "Johor Bahru"),
    ("KBR", "Sultan Ismail Petra Airport", "Kota Bharu"),
    ("BKI", "Kota Kinabalu International Airport", "Kota Kinabalu"),
    ("KUL", "Kuala Lumpur International Airport", "Kuala Lumpur/Sepang"),
    ("TGG", "Sultan Mahmud Airport", "Kuala Terengganu"),
    ("KUA", "Sultan Haji Ahmad Shah Airport", "Kuantan"),
    ("KCH", "Kuching International Airport", "Kuching"),
    ("LGK", "Langkawi International Airport", "Langkawi"),
    ("PEN", "Penang International Airport", "Penang"),
    ("SZB", "Sultan Abdul Aziz Shah Airport", "Subang"),
    ("MDL", "Mandalay International Airport", "Mandalay"),
    ("RGN", "Yangon International Airport", "Yangon"),
    ("NYT", "Naypyidaw International Airport", "Naypyidaw"),
    ("BSO", "Basco Airport", "Basco"),
    ("LLC", "Cagayan North International Airport", "Cagayan Special Economic Zone"),
    ("CEB", "Mactan–Cebu International Airport", "Lapu-Lapu"),
    ("CRK", "Clark International Airport", "Angeles"),
    ("DVO", "Francisco Bangoy International Airport", "Davao City"),
    ("GES", "General Santos International Airport", "General Santos"),
    ("ILO", "Iloilo International Airport", "Iloilo City"),
    ("KLO", "Kalibo International Airport", "Kalibo"),
    ("LAO", "Laoag International Airport", "Laoag"),
    ("MNL", "Ninoy Aquino International Airport", "Manila"),
    ("TAG", "Bohol–Panglao International Airport", "Panglao Island"),
    ("PPS", "Puerto Princesa International Airport", "Puerto Princesa"),
    ("SFS", "Subic Bay International Airport", "Olongapo"),
    ("ZAM", "Zamboanga International Airport", "Zamboanga City"),
    ("SIN", "Singapore Changi Airport", "Singapore"),
    ("XSP", "Seletar Airport", "Singapore"),
    ("BKK", "Suvarnabhumi Airport", "Bangkok/Samut Prakan"),
    ("DMK", "Don Mueang International Airport", "Bangkok"),
    ("CNX", "Chiang Mai International Airport", "Chiang Mai"),
    ("CEI", "Mae Fah Luang International Airport", "Chiang Rai"),
    ("UTP", "U-Tapao International Airport", "Rayong/Pattaya"),
    ("HDY", "Hat Yai International Airport", "Hat Yai"),
    ("KBV", "Krabi International Airport", "Krabi"),
    ("HKT", "Phuket International Airport", "Phuket"),
    ("URT", "Surat Thani International Airport", "Surat Thani"),
    ("USM", "Samui Airport", "Ko Samui"),
    ("UTH", "Udon Thani International Airport", "Udon Thani"),
    ("DAD", "Da Nang International Airport", "Da Nang"),
    ("HAN", "Noi Bai International Airport", "Hanoi"),
    ("SGN", "Tan Son Nhat International Airport", "Ho Chi Minh City"),
    ("VCA", "Can Tho International Airport", "Can Tho"),
    ("HPH", "Cat Bi International Airport", "Haiphong"),
    ("HUI", "Phu Bai International Airport", "Huế"),
    ("PQC", "Phu Quoc International Airport", "Phu Quoc"),
    ("CXR", "Cam Ranh International Airport", "Nha Trang"),
    ("VCL", "Chu Lai International Airport", "Quảng Nam"),
    ("KBL", "Hamid Karzai International Airport", "Kabul"),
    ("HEA", "Herat International Airport", "Herat"),
    ("KDH", "Kandahar International Airport", "Kandahar"),
    ("MZR", "Mazar-e Sharif International Airport", "Mazar-i-Sharif"),
    ("BAH", "Bahrain International Airport", "Manama"),
    ("ABD", "Abadan International Airport", "Abadan"),
    ("AWZ", "Ahvaz International Airport", "Ahvaz"),
    ("AJK", "Arak International Airport", "Arak"),
    ("ADU", "Ardabil Airport", "Ardabil"),
    ("PGU", "Persian Gulf Airport", "Asaluyeh"),
    ("BND", "Bandar Abbas International Airport", "Bandar Abbas"),
    ("XBJ", "Birjand International Airport", "Birjand"),
    ("BUZ", "Bushehr Airport", "Bushehr"),
    ("GBT", "Gorgan International Airport", "Gorgan"),
    ("HDM", "Hamadan International Airport", "Hamadan"),
    ("IIL", "Ilam Airport", "Ilam"),
    ("IFN", "Isfahan International Airport", "Isfahan"),
    ("KER", "Ayatollah Hashemi Rafsanjani Airport", "Kerman"),
    ("KSH", "Shahid Ashrafi Esfahani Airport", "Kermanshah"),
    ("KIH", "Kish Airport", "Kish Island"),
    ("ZBR", "Chabahar Konarak Airport", "Konarak"),
    ("LFM", "Lamerd Airport", "Lamerd"),
    ("LRR", "Larestan International Airport", "Lar"),
    ("MHD", "Mashhad International Airport", "Mashhad"),
    ("GSM", "Qeshm International Airport", "Qeshm"),
    ("RAS", "Rasht Airport", "Rasht"),
    ("SRY", "Dasht-e Naz Airport", "Sari"),
    ("SYZ", "Shiraz International Airport", "Shiraz"),
    ("TBZ", "Tabriz International Airport", "Tabriz"),
    ("IKA", "Imam Khomeini International Airport", "Tehran"),
    ("THR", "Mehrabad International Airport", "Tehran"),
    ("OMH", "Urmia Airport", "Urmia"),
    ("AZD", "Shahid Sadooghi Airport", "Yazd"),
    ("ZAH", "Zahedan Airport", "Zahedan"),
    ("NJF", "Al Najaf International Airport", "Al Najaf"),
    ("BGW", "Baghdad International Airport", "Baghdad"),
    ("BSR", "Basra International Airport", "Basra"),
    ("EBL", "Erbil International Airport", "Erbil"),
    ("OSM", "Mosul International Airport", "Mosul"),
    ("XNH", "Nasiriyah Airport", "Nasiriyah"),
    ("ISU", "Sulaimaniyah International Airport", "Sulaymaniyah"),
    ("ETM", "Ramon Airport", "Eilat"),
    ("HFA", "Haifa Airport", "Haifa"),
    ("TLV", "Ben Gurion Airport", "Tel Aviv"),
    ("AQJ", "King Hussein International Airport", "Aqaba"),
    ("AMM", "Queen Alia International Airport", "Amman"),
    ("KWI", "Kuwait International Airport", "Kuwait City"),
    ("BEY", "Beirut Rafic Hariri International Airport", "Beirut"),
    ("MCT", "Muscat International Airport", "Muscat"),
    ("SLL", "Salalah International Airport", "Salalah"),
    ("OHS", "Sohar International Airport", "Sohar"),
    ("DOH", "Hamad International Airport", "Doha"),
    ("AHB", "Abha International Airport", "Abha"),
    ("HOF", "Al-Ahsa International Airport", "Al-Ahsa"),
    ("AJF", "Al-Jawf Airport", "Al-Jawf"),
    ("ELQ", "Prince Nayef bin Abdulaziz International Airport", "Buraydah"),
    ("DMM", "King Fahd International Airport", "Dammam"),
    ("HAS", "Ha'il International Airport", "Ha'il"),
    ("JED", "King Abdulaziz International Airport", "Jeddah"),
    ("GIZ", "King Abdullah Bin Abdulaziz Airport", "Jizan"),
    ("MED", "Prince Mohammad Bin Abdulaziz International Airport", "Medina"),
    ("EAM", "Najran Airport", "Najran"),
    ("RUH", "King Khalid International Airport", "Riyadh"),
    ("TUU", "Prince Sultan bin Abdulaziz Airport", "Tabuk"),
    ("TIF", "Ta'if Airport", "Ta'if"),
    ("YNB", "Prince Abdul Mohsin bin Abdulaziz International Airport", "Yanbu"),
    ("ALP", "Aleppo International Airport", "Aleppo"),
    ("DAM", "Damascus International Airport", "Damascus"),
    ("LTK", "Bassel Al-Assad International Airport", "Latakia"),
    ("KAC", "Qamishli Airport", "Qamishli"),
    ("AUH", "Abu Dhabi International Airport", "Abu Dhabi"),
    ("AAN", "Al Ain International Airport", "Al Ain"),
    ("DWC", "Al-Maktoum International Airport", "Dubai"),
    ("DXB", "Dubai International Airport", "Dubai"),
    ("RKT", "Ras Al Khaimah International Airport", "Ras Al Khaimah"),
    ("SHJ", "Sharjah International Airport", "Sharjah"),
    ("ADE", "Aden International Airport", "Aden"),
    ("SAH", "Sana'a International Airport", "Sana'a"),
    ("GXF", "Seiyun Airport", "Seiyun"),
    ("ANR", "Antwerp International Airport", "Antwerp"),
    ("BRU", "Brussels Airport", "Brussels"),
    ("CRL", "Brussels South Charleroi Airport", "Brussels/Charleroi"),
    ("LGG", "Liège Airport", "Liège"),
    ("OST", "Ostend-Bruges International Airport", "Ostend/Bruges"),
    ("AJA", "Campo dell'Oro Airport", "Ajaccio"),
    ("BIA", "Poretta Airport", "Bastia"),
    ("BVA", "Beauvais-Tillé Airport", "Beauvais"),
    ("EGC", "Bergerac-Roumanière Airport", "Bergerac"),
    ("BZR", "Béziers Cap d'Agde Airport", "Béziers"),
    ("BIQ", "Biarritz Airport", "Biarritz"),
    ("BOD", "Mérignac Airport", "Bordeaux"),
    ("BES", "Brest Bretagne Airport", "Brest"),
    ("CCF", "Salvaza Airport", "Carcassonne"),
    ("XCR", "Châlons Vatry Airport", "Châlons-en-Champagne"),
    ("CMF", "Chambéry-Savoie Airport", "Chambéry"),
    ("DNR", "Pleurtuit Airport", "Dinard"),
    ("FSC", "Figari Sud-Corse Airport", "Figari"),
    ("GNB", "Grenoble-Isère Airport", "Grenoble"),
    ("LRH", "Île de Ré Airport", "Ile de Re"),
    ("LIL", "Lille Lesquin Airport", "Lille"),
    ("LIG", "Bellegarde Airport", "Limoges"),
    ("LYS", "Saint-Exupéry Airport", "Lyon"),
    ("MRS", "Provence Airport", "Marseille"),
    ("BSL", "Basel-Mulhouse-Freiburg Airport", "Mulhouse"),
    ("NTE", "Nantes Atlantique Airport", "Nantes"),
    ("NCE", "Côte d'Azur Airport", "Nice"),
    ("FNI", "Garons Airport", "Nîmes"),
    ("CDG", "Charles de Gaulle Airport", "Paris"),
    ("ORY", "Orly Airport", "Paris"),
    ("PUF", "Uzein Airport", "Pau"),
    ("PGF", "Llabanère Airport", "Perpignan"),
    ("PIS", "Biard Airport", "Poitiers"),
    ("RDZ", "Marcillac Airport", "Rodez"),
    ("EBU", "Bouthéon Airport", "Saint Etienne"),
    ("SXB", "Strasbourg Airport", "Strasbourg"),
    ("TLN", "Hyères Le Palyvestre Airport", "Toulon"),
    ("TLS", "Blagnac Airport", "Toulouse"),
    ("TUF", "Tours Loire Valley Airport", "Tours"),
    ("GIB", "North Front Airport", "Gibraltar"),
    ("ACI", "Alderney Airport", "Alderney"),
    ("GCI", "Guernsey Airport", "Guernsey"),
    ("JER", "Jersey Airport", "Jersey"),
    ("ORK", "Cork Airport", "Cork"),
    ("DUB", "Dublin Airport", "Dublin"),
    ("KIR", "Kerry Airport", "Kerry"),
    ("NOC", "Ireland West Airport Knock", "Knock"),
    ("SNN", "Shannon Airport", "Shannon"),
    ("IOM", "Isle of Man Airport", "Isle of Man"),
    ("LUX", "Findel Airport", "Luxembourg City"),
    ("AMS", "Amsterdam Airport Schiphol", "Amsterdam"),
    ("EIN", "Eindhoven Airport", "Eindhoven"),
    ("GRQ", "Groningen Airport Eelde", "Groningen"),
    ("MST", "Maastricht-Aachen Airport", "Maastricht"),
    ("RTM", "Rotterdam The Hague Airport", "Rotterdam"),
    ("BYJ", "Beja Airport", "Beja"),
    ("FAO", "Faro Airport", "Faro"),
    ("FNC", "Madeira Airport", "Funchal"),
    ("PXO", "Porto Santo Airport", "Porto Santo Island"),
    ("LIS", "Humberto Delgado Airport", "Lisbon"),
    ("OPO", "Francisco Sá Carneiro Airport", "Porto"),
    ("PDL", "João Paulo II Airport", "Ponta Delgada"),
    ("TER", "Terceira Airport", "Terceira Island"),
    ("LCG", "Alvedro Airport", "A Coruña"),
    ("ALC", "Alicante Airport", "Alicante"),
    ("LEI", "Almería International Airport", "Almeria"),
    ("OVD", "Asturias Airport", "Asturias"),
    ("BCN", "Barcelona Airport", "Barcelona"),
    ("BIO", "Bilbao Airport", "Bilbao"),
    ("CDT", "Castellón–Costa Azahar Airport", "Castellón de la Plana"),
    ("FUE", "Fuerteventura Airport", "Fuerteventura"),
    ("GRO", "Girona-Costa Brava Airport", "Girona"),
    ("LPA", "Gran Canaria Airport", "Gran Canaria"),
    ("GRX", "Federico García Lorca Granada Airport", "Granada"),
    ("HSK", "Huesca-Pirineos Airport", "Huesca"),
    ("IBZ", "Ibiza Airport", "Ibiza"),
    ("XRY", "Jerez Airport", "Jerez de la Frontera"),
    ("SPC", "La Palma Airport", "La Palma"),
    ("ACE", "Lanzarote Airport", "Lanzarote"),
    ("ILD", "Alguaire Airport", "Lleida"),
    ("MAD", "Madrid-Barajas Airport", "Madrid"),
    ("AGP", "Málaga Airport", "Málaga"),
    ("MAH", "Menorca Airport", "Menorca"),
    ("RMU", "Región de Murcia International Airport", "Murcia"),
    ("PMI", "Palma de Mallorca Airport", "Palma de Mallorca"),
    ("PNA", "Pamplona Airport", "Pamplona"),
    ("REU", "Reus Airport", "Reus"),
    ("SDR", "Santander Airport", "Santander"),
    ("SCQ", "Santiago de Compostela Airport", "Santiago de Compostela"),
    ("SVQ", "Seville Airport", "Seville"),
    ("TFN", "Tenerife North Airport", "Tenerife"),
    ("TFS", "Tenerife South Airport", "Tenerife"),
    ("VLC", "Valencia Airport", "Valencia"),
    ("VLL", "Valladolid Airport", "Valladolid"),
    ("VGO", "Vigo–Peinador Airport", "Vigo"),
    ("VIT", "Vitoria Airport", "Vitoria-Gasteiz"),
    ("ZAZ", "Zaragoza Airport", "Zaragoza"),
    ("GRZ", "Graz Airport", "Graz"),
    ("KLU", "Klagenfurt Airport", "Klagenfurt"),
    ("INN", "Innsbruck Airport", "Innsbruck"),
    ("LNZ", "Linz Airport", "Linz"),
    ("SZG", "Salzburg Airport", "Salzburg"),
    ("VIE", "Vienna International Airport", "Vienna"),
    ("BRQ", "Brno-Tuřany Airport", "Brno"),
    ("KLV", "Karlovy Vary Airport", "Karlovy Vary"),
    ("OSR", "Leoš Janáček Ostrava Airport", "Ostrava"),
    ("PRG", "Prague Václav Havel Airport", "Prague"),
    ("PED", "Pardubice Airport", "Pardubice"),
    ("FKB", "Karlsruhe/Baden-Baden Airport", "Baden-Baden/Karlsruhe"),
    ("BER", "Berlin Brandenburg Airport", "Berlin"),
    ("BRE", "Bremen Airport", "Bremen"),
    ("CGN", "Cologne/Bonn Airport", "Cologne/Bonn"),
    ("DTM", "Dortmund Airport", "Dortmund"),
    ("DUS", "Düsseldorf Airport", "Düsseldorf"),
    ("FRA", "Frankfurt Airport", "Frankfurt"),
    ("HHN", "Frankfurt-Hahn Airport", "Frankfurt"),
    ("MLH", "EuroAirport Basel–Mulhouse–Freiburg", "Freiburg im Breisgau"),
    ("BSL", "EuroAirport Basel–Mulhouse–Freiburg", "Freiburg im Breisgau"),
    ("EAP", "EuroAirport Basel–Mulhouse–Freiburg", "Freiburg im Breisgau"),
    ("FDH", "Friedrichshafen Airport", "Friedrichshafen"),
    ("HAM", "Hamburg Airport", "Hamburg"),
    ("HAJ", "Langenhagen Airport", "Hanover"),
    ("LEJ", "Leipzig/Halle Airport", "Leipzig"),
    ("LBC", "Lübeck Airport", "Lübeck"),
    ("FMM", "Memmingen Airport", "Memmingen"),
    ("MUC", "Munich Airport", "Munich"),
    ("NUE", "Albrecht Dürer Airport", "Nuremberg"),
    ("STR", "Stuttgart Airport", "Stuttgart"),
    ("NRN", "Weeze Airport", "Weeze"),
    ("BUD", "Budapest Ferenc Liszt International Airport", "Budapest"),
    ("DEB", "Debrecen International Airport", "Debrecen"),
    ("SOB", "Hévíz-Balaton Airport", "Hévíz"),
    ("QGY", "Győr-Pér International Airport", "Győr"),
    ("QPJ", "Pécs-Pogány International Airport", "Pécs"),
    ("BTS", "M. R. Štefánik Airport", "Bratislava"),
    ("KSC", "Košice International Airport", "Košice"),
    ("PZY", "Piešťany Airport", "Piešťany"),
    ("TAT", "Poprad-Tatry Airport", "Poprad"),
    ("SLD", "Sliač Airport", "Sliač"),
    ("ILZ", "Žilina Airport", "Žilina"),
    ("BSL", "EuroAirport Basel–Mulhouse–Freiburg", "Basel"),
    ("BRN", "Bern-Belp Airport", "Bern"),
    ("GVA", "Geneva International Airport", "Geneva"),
    ("ACH", "St. Gallen-Altenrhein Airport", "St. Gallen"),
    ("ZRH", "Zurich Airport", "Zurich"),
    ("BZG", "Bydgoszcz Ignacy Jan Paderewski Airport", "Bydgoszcz"),
    ("GDN", "Gdańsk Lech Wałęsa Airport", "Gdańsk"),
    ("KTW", "Katowice International Airport", "Katowice"),
    ("KRK", "John Paul II International Airport Kraków-Balice", "Kraków"),
    ("LUZ", "Lublin Airport", "Lublin"),
    ("LCJ", "Łódź Władysław Reymont Airport", "Łódź"),
    ("POZ", "Poznań Ławica Airport", "Poznań"),
    ("RZE", "Rzeszów-Jasionka Airport", "Rzeszów"),
    ("SZZ", "Szczecin-Goleniów ""Solidarność"" Airport", "Szczecin"),
    ("WAW", "Frédéric Chopin Airport", "Warsaw"),
    ("WMI", "Modlin Airport", "Warsaw"),
    ("WRO", "Copernicus Airport Wrocław", "Wrocław"),
    ("BWK", "Brač Airport", "Brač"),
    ("DBV", "Dubrovnik Airport", "Dubrovnik"),
    ("LSZ", "Lošinj Airport", "Mali Lošinj"),
    ("OSI", "Osijek Airport", "Osijek"),
    ("PUY", "Pula Airport", "Pula"),
    ("RJK", "Rijeka Airport", "Rijeka"),
    ("SPU", "Split Airport", "Split"),
    ("ZAD", "Zadar Airport", "Zadar"),
    ("ZAG", "Franjo Tuđman Airport", "Zagreb"),
    ("LCA", "Larnaca International Airport", "Larnaca"),
    ("PFO", "Paphos International Airport", "Paphos"),
    ("ECN", "Ercan International Airport", "North Nicosia"),
    ("ATH", "Athens International Airport", "Athens"),
    ("CHQ", "Chania International Airport", "Chania"),
    ("JKH", "Chios Island National Airport", "Chios Island"),
    ("CFU", "Ioannis Kapodistrias Airport", "Corfu"),
    ("HER", "Heraklion International Airport", "Heraklion"),
    ("KLX", "Kalamata International Airport", "Kalamata"),
    ("AOK", "Karpathos Island National Airport", "Karpathos Island"),
    ("KVA", "Kavala International Airport", "Kavala"),
    ("EFL", "Kefalonia Island International Airport", "Kefalonia Island"),
    ("KGS", "Kos Island International Airport", "Kos Island"),
    ("JMK", "Mykonos Island National Airport", "Mykonos Island"),
    ("MJT", "Mytilene International Airport", "Mytilene"),
    ("PVK", "Aktion National Airport", "Preveza"),
    ("RHO", "Rhodes International Airport", "Rhodes"),
    ("SMI", "Samos International Airport", "Samos"),
    ("JTR", "Santorini (Thira) National Airport", "Santorini"),
    ("JSI", "Skiathos Island National Airport", "Skiathos Island"),
    ("SKU", "Skyros Island National Airport", "Skyros Island"),
    ("SKG", "Thessaloniki International Airport", "Thessaloniki"),
    ("VOL", "Nea Anchialos National Airport", "Volos"),
    ("ZTH", "Zakynthos International Airport", "Zakynthos"),
    ("AHO", "Fertilia Airport", "Alghero"),
    ("AOI", "Ancona Airport", "Ancona"),
    ("BRI", "Palese Airport", "Bari"),
    ("BGY", "Orio al Serio Airport", "Bergamo"),
    ("BLQ", "Bologna Airport", "Bologna"),
    ("VBS", "Brescia Airport", "Brescia"),
    ("BDS", "Brindisi Airport", "Brindisi"),
    ("CAG", "Cagliari Airport", "Cagliari"),
    ("CTA", "Fontanarossa Airport", "Catania"),
    ("CUF", "Cuneo Levaldigi Airport", "Cuneo"),
    ("FLR", "Peretola Airport", "Florence"),
    ("GOA", "Cristoforo Colombo Airport", "Genoa"),
    ("SUF", "Lamezia Terme Airport", "Lamezia"),
    ("LIN", "Linate Airport", "Milan"),
    ("MXP", "Malpensa Airport", "Milan"),
    ("NAP", "Capodichino Airport", "Naples"),
    ("OLB", "Costa Smeralda Airport", "Olbia"),
    ("PMO", "Palermo Airport", "Palermo"),
    ("PMF", "Giuseppe Verdi Airport", "Parma"),
    ("PEG", "San Egidio Airport", "Perugia"),
    ("PSR", "Abruzzo Airport", "Pescara"),
    ("PSA", "Galileo Galilei Airport", "Pisa"),
    ("RMI", "Federico Fellini Airport", "Rimini"),
    ("FCO", "Leonardo da Vinci-Fiumicino Airport", "Rome"),
    ("CIA", "Rome Ciampino Airport", "Rome"),
    ("TPS", "Vincenzo Florio Airport", "Trapani"),
    ("TRS", "Friuli Venezia Giulia Airport", "Trieste"),
    ("TRN", "Caselle Airport", "Turin"),
    ("VCE", "Venice Marco Polo Airport", "Venice"),
    ("VRN", "Verona Airport", "Verona"),
    ("MLA", "Malta International Airport", "Valletta"),
    ("LJU", "Ljubljana Jože Pučnik Airport", "Ljubljana"),
    ("MBX", "Maribor Edvard Rusjan Airport", "Maribor"),
    ("POW", "Portorož Airport", "Portorož"),
    ("TIA", "Tirana International Airport Nënë Tereza", "Tirana"),
    ("EVN", "Zvartnots International Airport", "Yerevan"),
    ("LWN", "Shirak Airport", "Gyumri"),
    ("GYD", "Heydar Aliyev International Airport", "Baku"),
    ("KVD", "Ganja International Airport", "Ganja"),
    ("NAJ", "Nakhchivan Airport", "Nakhchivan"),
    ("GBB", "Qabala International Airport", "Qabala"),
    ("LLK", "Lankaran International Airport", "Lankaran"),
    ("ZTU", "Zaqatala International Airport", "Zaqatala"),
    ("GNA", "Hrodna Airport", "Grodno"),
    ("GME", "Gomel Airport", "Gomel"),
    ("MSQ", "Minsk International Airport", "Minsk"),
    ("BNX", "Banja Luka International Airport", "Banja Luka"),
    ("SJJ", "Sarajevo International Airport", "Sarajevo"),
    ("TZL", "Tuzla International Airport", "Tuzla"),
    ("OMO", "Mostar International Airport", "Mostar"),
    ("BOJ", "Burgas Airport", "Burgas"),
    ("PDV", "Plovdiv Airport", "Plovdiv"),
    ("SOF", "Sofia Airport", "Sofia"),
    ("VAR", "Varna Airport", "Varna"),
    ("TLL", "Lennart Meri Tallinn Airport", "Tallinn"),
    ("TAY", "Tartu Airport", "Tartu"),
    ("UGAM", "Ambrolauri Airport", "Ambrolauri"),
    ("BUS", "Batumi International Airport", "Batumi"),
    ("KUT", "Kutaisi International Airport", "Kutaisi"),
    ("UGMS", "Queen Tamar Airport", "Mestia"),
    ("UGSA", "Natakhtari Airfield", "Natakhtari"),
    ("SUI", "Sukhumi Babushara Airport", "Sokhumi"),
    ("TBS", "Tbilisi International Airport", "Tbilisi"),
    ("PRN", "Pristina International Airport", "Pristina"),
    ("RIX", "Riga International Airport", "Riga"),
    ("VNT", "Ventspils International Airport", "Ventspils"),
    ("KUN", "Kaunas Airport", "Kaunas"),
    ("PLQ", "Palanga International Airport", "Palanga"),
    ("SQQ", "Šiauliai International Airport", "Šiauliai"),
    ("VNO", "Vilnius International Airport", "Vilnius"),
    ("KIV", "Chişinău International Airport", "Chişinău"),
    ("BCM", "George Enescu International Airport", "Bacau"),
    ("OTP", "Henri Coanda International Airport", "Bucharest"),
    ("CLJ", "Cluj-Napoca International Airport", "Cluj-Napoca"),
    ("CND", "Mihail Kogălniceanu International Airport", "Constanța"),
    ("CRA", "Craiova International Airport", "Craiova"),
    ("IAS", "Iași International Airport", "Iași"),
    ("OMR", "Oradea International Airport", "Oradea"),
    ("SBZ", "Sibiu International Airport", "Sibiu"),
    ("TSR", "Traian Vuia International Airport", "Timișoara"),
    ("TGD", "Podgorica Airport", "Podgorica"),
    ("TIV", "Tivat Airport", "Tivat"),
    ("OHD", "Ohrid St. Paul the Apostle Airport", "Ohrid"),
    ("SKP", "Skopje Alexander the Great Airport", "Skopje"),
    ("ABA", "Abakan International Airport", "Abakan"),
    ("DYR", "Ugolny Airport", "Anadyr"),
    ("AAQ", "Anapa Airport", "Anapa"),
    ("ARH", "Talagi Airport", "Arkhangelsk"),
    ("ASF", "Narimanovo Airport", "Astrakhan"),
    ("BAX", "Barnaul Airport", "Barnaul"),
    ("EGO", "Belgorod International Airport", "Belgorod"),
    ("BQS", "Ignatyevo Airport", "Blagoveshchensk"),
    ("BTK", "Bratsk Airport", "Bratsk"),
    ("BZK", "Bryansk International Airport", "Bryansk"),
    ("CSY", "Cheboksary Airport", "Cheboksary"),
    ("CEK", "Chelyabinsk Airport", "Chelyabinsk"),
    ("CEE", "Cherepovets Airport", "Cherepovets"),
    ("HTA", "Kadala Airport", "Chita"),
    ("ESL", "Elista Airport", "Elista"),
    ("IKT", "Irkutsk Airport", "Irkutsk"),
    ("GRV", "Grozny Airport", "Grozny"),
    ("KGD", "Khrabrovo Airport", "Kaliningrad"),
    ("KZN", "Kazan Airport", "Kazan"),
    ("KHV", "Khabarovsk Novy Airport", "Khabarovsk"),
    ("KXK", "Komsomolsk-on-Amur Airport", "Komsomolsk-on-Amur"),
    ("KRR", "Pashkovsky Airport", "Krasnodar"),
    ("KJA", "Yemelyanovo International Airport", "Krasnoyarsk"),
    ("URS", "Kursk Vostochny Airport", "Kursk"),
    ("GDX", "Sokol Airport", "Magadan"),
    ("MQF", "Magnitogorsk International Airport", "Magnitogorsk"),
    ("MCX", "Uytash Airport", "Makhachkala"),
    ("MRV", "Mineralnye Vody Airport", "Mineralnye Vody"),
    ("DME", "Domodedovo International Airport", "Moscow"),
    ("SVO", "Sheremetyevo International Airport", "Moscow"),
    ("VKO", "Vnukovo Airport", "Moscow"),
    ("MMK", "Murmansk Airport", "Murmansk"),
    ("NAL", "Nalchik Airport", "Nalchik"),
    ("NJC", "Nizhnevartovsk Airport", "Nizhnevartovsk"),
    ("NBC", "Begishevo Airport", "Nizhnekamsk"),
    ("GOJ", "Strigino Airport", "Nizhny Novgorod"),
    ("NOZ", "Spichenkovo Airport", "Novokuznetsk"),
    ("OVB", "Tolmachevo Airport", "Novosibirsk"),
    ("OMS", "Omsk Tsentralny Airport", "Omsk"),
    ("REN", "Orenburg Tsentralny Airport", "Orenburg"),
    ("OSW", "Orsk Airport", "Orsk"),
    ("PEE", "Perm International Airport", "Perm"),
    ("PES", "Petrozavodsk Airport", "Petrozavodsk"),
    ("PVS", "Provideniya Bay Airport", "Provideniya"),
    ("PKC", "Yelizovo Airport", "Petropavlovsk-Kamchatsky"),
    ("PKV", "Pskov Airport", "Pskov"),
    ("ROV", "Platov International Airport", "Rostov-on-Don"),
    ("LED", "Pulkovo Airport", "Saint Petersburg"),
    ("KUF", "Samara Kurumoch Airport", "Samara"),
    ("GSV", "Saratov Gagarin Airport", "Saratov"),
    ("AER", "Sochi International Airport", "Sochi"),
    ("STW", "Stavropol Shpakovskoye Airport", "Stavropol"),
    ("SGC", "Surgut International Airport", "Surgut"),
    ("SCW", "Syktyvkar Airport", "Syktyvkar"),
    ("TOF", "Bogashevo Airport", "Tomsk"),
    ("TJM", "Roshchino International Airport", "Tyumen"),
    ("UUD", "Baikal International Airport", "Ulan-Ude"),
    ("ULV", "Ulyanovsk Baratayevka Airport", "Ulyanovsk"),
    ("UFA", "Ufa International Airport", "Ufa"),
    ("VVO", "Vladivostok International Airport", "Vladivostok"),
    ("OGZ", "Beslan Airport", "Vladikavkaz"),
    ("VOG", "Volgograd International Airport", "Volgograd"),
    ("VOZ", "Voronezh International Airport", "Voronezh"),
    ("YKS", "Yakutsk Airport", "Yakutsk"),
    ("IAR", "Tunoshna Airport", "Yaroslavl"),
    ("SVX", "Koltsovo International Airport", "Yekaterinburg"),
    ("UUS", "Yuzhno-Sakhalinsk Airport", "Yuzhno-Sakhalinsk"),
    ("BEG", "Belgrade Nikola Tesla Airport", "Belgrade"),
    ("INI", "Niš Constantine the Great Airport", "Niš"),
    ("KVO", "Morava Airport", "Kraljevo"),
    ("ADA", "Şakirpaşa Airport", "Adana"),
    ("ESB", "Esenboğa International Airport", "Ankara"),
    ("AYT", "Antalya Airport", "Antalya"),
    ("BJV", "Milas-Bodrum Airport", "Bodrum"),
    ("YEI", "Yenişehir Airport", "Bursa"),
    ("DLM", "Dalaman Airport", "Dalaman"),
    ("GZT", "Oğuzeli Airport", "Gaziantep"),
    ("IST", "Istanbul Airport", "Istanbul"),
    ("SAW", "Sabiha Gökçen International Airport", "Istanbul"),
    ("ADB", "Adnan Menderes Airport", "İzmir"),
    ("ASR", "Erkilet Airport", "Kayseri"),
    ("KYA", "Konya Airport", "Konya"),
    ("KZR", "Zafer Airport", "Kütahya"),
    ("MLX", "Erhaç Airport", "Malatya"),
    ("NAV", "Kapadokya Airport", "Nevşehir"),
    ("SZF", "Samsun-Çarşamba Airport", "Samsun"),
    ("TZX", "Trabzon Airport", "Trabzon"),
    ("ONQ", "Zonguldak Airport", "Zonguldak"),
    ("KBP", "Boryspil International Airport", "Kyiv"),
    ("CWC", "Chernivtsi International Airport", "Chernivtsi"),
    ("DNK", "Dnipropetrovsk International Airport", "Dnipro"),
    ("IFO", "Ivano-Frankivsk International Airport", "Ivano-Frankivsk"),
    ("HRK", "Kharkiv International Airport", "Kharkiv"),
    ("KWG", "Kryvyi Rih International Airport", "Kryvyi Rih"),
    ("IEV", "Kyiv Zhuliany International Airport", "Kyiv"),
    ("LWO", "Lviv Danylo Halytskyi International Airport", "Lviv"),
    ("NLV", "Mykolaiv International Airport", "Mykolaiv"),
    ("ODS", "Odesa International Airport", "Odessa"),
    ("PLV", "Poltava Airport", "Poltava"),
    ("SIP", "Simferopol International Airport", "Simferopol"),
    ("UDJ", "Uzhhorod International Airport", "Uzhhorod"),
    ("OZH", "Zaporizhzhia International Airport", "Zaporizhzhia"),
    ("AAL", "Aalborg Airport", "Aalborg"),
    ("AAR", "Aarhus Airport", "Aarhus"),
    ("BLL", "Billund Airport", "Billund"),
    ("CPH", "Copenhagen Airport", "Copenhagen"),
    ("FAE", "Vágar Airport", "Vágar"),
    ("MHQ", "Mariehamn Airport", "Åland"),
    ("HEL", "Helsinki-Vantaa Airport", "Helsinki"),
    ("KTT", "Kittilä Airport", "Kittilä"),
    ("KUO", "Kuopio Airport", "Kuopio"),
    ("KAO", "Kuusamo Airport", "Kuusamo"),
    ("LPP", "Lappeenranta Airport", "Lappeenranta"),
    ("OUL", "Oulu Airport", "Oulu"),
    ("RVN", "Rovaniemi Airport", "Rovaniemi"),
    ("TMP", "Tampere-Pirkkala Airport", "Tampere"),
    ("TKU", "Turku Airport", "Turku"),
    ("VAA", "Vaasa Airport", "Vaasa"),
    ("AEY", "Akureyri Airport", "Akureyri"),
    ("KEF", "Keflavik International Airport", "Reykjavik"),
    ("RKV", "Reykjavik Airport", "Reykjavik"),
    ("AES", "Ålesund Airport", "Ålesund"),
    ("BGO", "Bergen Airport", "Bergen"),
    ("BOO", "Bodø Airport", "Bodø"),
    ("HAU", "Haugesund Airport", "Haugesund"),
    ("KRS", "Kristiansand Airport, Kjevik", "Kristiansand"),
    ("KSU", "Kristiansund Airport, Kvernberget", "Kristiansand"),
    ("OSL", "Oslo Airport-Gardermoen", "Oslo"),
    ("TRF", "Sandefjord Airport", "Oslo"),
    ("SVG", "Stavanger Airport", "Stavanger"),
    ("TOS", "Tromsø Airport", "Tromsø"),
    ("TRD", "Trondheim Airport", "Trondheim"),
    ("GOT", "Göteborg Landvetter Airport", "Gothenburg"),
    ("LLA", "Luleå Airport", "Luleå"),
    ("MMX", "Malmö Airport", "Malmö"),
    ("NRK", "Norrköping Airport", "Norrköping"),
    ("OSD", "Åre Östersund Airport", "Östersund"),
    ("ARN", "Stockholm-Arlanda Airport", "Stockholm"),
    ("BMA", "Stockholm-Bromma Airport", "Stockholm"),
    ("NYO", "Stockholm-Skavsta Airport", "Stockholm"),
    ("VST", "Stockholm-Västerås Airport", "Stockholm"),
    ("SDL", "Sundsvall-Timrå Airport", "Sundsvall"),
    ("UME", "Umeå Airport", "Umeå"),
    ("VXO", "Växjö Airport", "Växjö"),
    ("VBY", "Visby Airport", "Visby"),
    ("BHX", "Birmingham International Airport", "Birmingham"),
    ("BOH", "Bournemouth Airport", "Bournemouth"),
    ("BRS", "Bristol Airport", "Bristol"),
    ("CWL", "Cardiff Airport", "Cardiff"),
    ("DSA", "Robin Hood Airport Doncaster Sheffield", "Doncaster/Sheffield"),
    ("MME", "Durham Tees Valley Airport", "Middlesbrough"),
    ("EMA", "East Midlands Airport", "Nottingham/Leicester"),
    ("EXT", "Exeter International Airport", "Exeter"),
    ("LBA", "Leeds Bradford International Airport", "Leeds/Bradford"),
    ("LPL", "Liverpool John Lennon Airport", "Liverpool"),
    ("LCY", "London City Airport", "London"),
    ("LGW", "Gatwick Airport", "London"),
    ("LHR", "Heathrow Airport", "London"),
    ("LTN", "Luton Airport", "London"),
    ("SEN", "Southend Airport", "London"),
    ("STN", "Stansted Airport", "London"),
    ("MAN", "Manchester Airport", "Manchester"),
    ("NCL", "Newcastle Airport", "Newcastle upon Tyne"),
    ("NQY", "Newquay Cornwall Airport", "Newquay"),
    ("NWI", "Norwich International Airport", "Norwich"),
    ("SOU", "Southampton Airport", "Southampton"),
    ("ABZ", "Aberdeen Airport", "Aberdeen"),
    ("EDI", "Edinburgh Airport", "Edinburgh"),
    ("GLA", "Glasgow International Airport", "Glasgow"),
    ("PIK", "Glasgow Prestwick Airport", "Glasgow"),
    ("INV", "Inverness Airport", "Inverness"),
    ("BFS", "Belfast International Airport", "Belfast"),
    ("BHD", "George Best Belfast City Airport", "Belfast"),
    ("LDY", "City of Derry Airport", "Derry"),
    ("PPG", "Pago Pago International Airport", "Pago Pago"),
    ("ADL", "Adelaide Airport", "Adelaide"),
    ("BNE", "Brisbane Airport", "Brisbane"),
    ("BME", "Broome International Airport", "Broome"),
    ("CNS", "Cairns Airport", "Cairns"),
    ("CBR", "Canberra Airport", "Canberra"),
    ("DRW", "Darwin International Airport", "Darwin"),
    ("AVV", "Avalon Airport", "Geelong"),
    ("OOL", "Gold Coast Airport", "Gold Coast"),
    ("HBA", "Hobart International Airport", "Hobart"),
    ("MEL", "Melbourne Airport", "Melbourne"),
    ("NTL", "Newcastle Airport", "Newcastle"),
    ("PER", "Perth Airport", "Perth"),
    ("PHE", "Port Hedland International Airport", "Port Hedland"),
    ("SYD", "Sydney Airport", "Sydney"),
    ("TSV", "Townsville International Airport", "Townsville"),
    ("XCH", "Christmas Island Airport", "Christmas Island"),
    ("CCK", "Cocos (Keeling) Islands Airport", "Cocos (Keeling) Islands"),
    ("RAR", "Rarotonga Airport", "Rarotonga"),
    ("IPC", "Mataveri International Airport", "Hanga Roa"),
    ("NAN", "Nadi International Airport", "Nadi"),
    ("SUV", "Nausori International Airport", "Suva"),
    ("PPT", "Faa'a International Airport", "Papeete"),
    ("GUM", "Antonio B. Won Pat International Airport", "Hagåtña"),
    ("CXI", "Cassidy International Airport", "Kiritimati"),
    ("TRW", "Bonriki International Airport", "Tarawa"),
    ("KWA", "Bucholz Army Airfield", "Kwajalein"),
    ("MAJ", "Marshall Islands International Airport", "Majuro"),
    ("TKK", "Chuuk International Airport", "Chuuk"),
    ("KSA", "Kosrae International Airport", "Kosrae"),
    ("PNI", "Pohnpei International Airport", "Pohnpei"),
    ("YAP", "Yap International Airport", "Yap"),
    ("INU", "Nauru International Airport", "Yaren"),
    ("NOU", "La Tontouta International Airport", "Nouméa"),
    ("AKL", "Auckland Airport", "Auckland"),
    ("CHC", "Christchurch International Airport", "Christchurch"),
    ("DUD", "Dunedin International Airport", "Dunedin"),
    ("ZQN", "Queenstown Airport", "Queenstown"),
    ("WLG", "Wellington International Airport", "Wellington"),
    ("NLK", "Norfolk Island Airport", "Norfolk Island"),
    ("ROP", "Rota International Airport", "Rota Island"),
    ("SPN", "Saipan International Airport", "Saipan Island"),
    ("TIQ", "Tinian International Airport", "Tinian Island"),
    ("IUE", "Niue International Airport", "Alofi"),
    ("ROR", "Roman Tmetuchl International Airport", "Koror"),
    ("POM", "Jacksons International Airport", "Port Moresby"),
    ("HGU", "Mount Hagen Airport", "Mount Hagen"),
    ("APW", "Faleolo International Airport", "Apia"),
    ("HIR", "Honiara International Airport", "Honiara"),
    ("TBU", "Fuaʻamotu International Airport", "Nukuʻalofa"),
    ("VAV", "Vava'u International Airport", "Vavaʻu"),
    ("FUN", "Funafuti International Airport", "Funafuti"),
    ("SON", "Santo-Pekoa International Airport", "Luganville"),
    ("VLI", "Bauerfield International Airport", "Port Vila"),
    ("FUT", "Pointe Vele Airport", "Futuna"),
    ("WLS", "Hihifo Airport", "Wallis")
  ;
